runtime: nodejs20
service: "fe-projek-akhir"
instance_class: F1

handlers:
  # Serve static files
  - url: /static/(.*)
    static_files: build/static/\1
    upload: build/static/.*
    secure: always

  # Serve other static files (favicon, manifest, etc)
  - url: /(.*\.(ico|png|jpg|json|txt|woff2?))
    static_files: build/\1
    upload: build/.*\.(ico|png|jpg|json|txt|woff2?)
    secure: always

  # Serve index.html for all other routes
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always


