steps:
  # Mengambil file .env dari Cloud Storage bucket
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://projekakhir/.env", ".env"]

  # Verifikasi file .env
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Verifying .env file:"
        cat .env
        echo "File size:"
        ls -l .env
        echo "Moving .env to be directory:"
        mv .env be/.env
        echo "Verifying final location:"
        ls -l be/.env

  # Membuat dan mengatur secret
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Membuat secret jika belum ada
        if ! gcloud secrets describe app-env > /dev/null 2>&1; then
          echo "Creating new secret: app-env"
          gcloud secrets create app-env --replication-policy="automatic"
        fi

        # Mengupdate secret dengan isi file .env
        echo "Updating secret with .env content"
        cat be/.env | gcloud secrets versions add app-env --data-file=-

        # Mendapatkan project number
        PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)')
        echo "Project Number: $PROJECT_NUMBER"

        # Memberikan akses ke Cloud Run service account
        echo "Granting access to Cloud Run service account"
        gcloud secrets add-iam-policy-binding app-env \
          --member="serviceAccount:${PROJECT_NUMBER}-compute@developer.gserviceaccount.com" \
          --role="roles/secretmanager.secretAccessor"

  # Membuat image dengan perintah "cloud build -t gcr.io/$PROJECT_ID/projek-akhir ."
  # Project ID akan secara otomatis terisi ketika melakukan deploy di project yg dipilih
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/projek-akhir", "."]
    dir: "be"

  # Verifikasi file .env dan environment variables di dalam image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "=== Checking .env file inside the image ==="
        docker run --rm gcr.io/$PROJECT_ID/projek-akhir ls -la /app/.env
        echo -e "\n=== Content of .env file inside the image ==="
        docker run --rm gcr.io/$PROJECT_ID/projek-akhir cat /app/.env
        echo -e "\n=== Testing environment variables inside the image ==="
        docker run --rm gcr.io/$PROJECT_ID/projek-akhir node -e "
          require('dotenv').config();
          console.log('DB_HOST:', process.env.DB_HOST);
          console.log('DB_NAME:', process.env.DB_NAME);
          console.log('DB_USERNAME:', process.env.DB_USERNAME);
          console.log('DB_PASSWORD:', process.env.DB_PASSWORD ? 'Set' : 'Not Set');
          console.log('ACCESS_TOKEN_SECRET:', process.env.ACCESS_TOKEN_SECRET ? 'Set' : 'Not Set');
          console.log('REFRESH_TOKEN_SECRET:', process.env.REFRESH_TOKEN_SECRET ? 'Set' : 'Not Set');
        "

  # Meng-upload/push image yg telah dibuat ke Artifact Registry
  # Pada bagian ini, dijalankan perintah "docker push 'gcr.io/$PROJECT_ID/projek-akhir'"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/projek-akhir"]

  # Melakukan deploy ke cloud run dengan environment variables dari Secret Manager
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "projek-akhir"
      - "--image"
      - "gcr.io/$PROJECT_ID/projek-akhir"
      - "--timeout"
      - "360s"
      - "--port"
      - "5001"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--set-secrets"
      - "/app/.env=projects/$PROJECT_ID/secrets/app-env:latest"

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY
